/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Me
     * @description The signed-in user, their organizations and roles (for the org switcher), and the active
     *     organization's permissions.
     */
    get: operations["get_me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Live */
    get: operations["health_live"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ready */
    get: operations["health_ready"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** CheckResult */
    CheckResult: {
      /** Error */
      error?: string | null;
      /** Latency Ms */
      latency_ms: number;
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "error";
    };
    /** ErrorBody */
    ErrorBody: {
      /** Code */
      code: string;
      /** Details */
      details?: unknown;
      /** Message */
      message: string;
    };
    /** ErrorResponse */
    ErrorResponse: {
      error: components["schemas"]["ErrorBody"];
    };
    /** LivenessResponse */
    LivenessResponse: {
      /**
       * Status
       * @constant
       */
      status: "ok";
    };
    /** MeResponse */
    MeResponse: {
      /** Active Organization Id */
      active_organization_id: string | null;
      /** Active Roles */
      active_roles: components["schemas"]["OrgRole"][];
      /** Is Platform Admin */
      is_platform_admin: boolean;
      /** Memberships */
      memberships: components["schemas"]["MembershipOut"][];
      /** Permissions */
      permissions: string[];
      user: components["schemas"]["MeUser"];
    };
    /** MeUser */
    MeUser: {
      /** Email */
      email: string;
      /** Full Name */
      full_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
    };
    /** MembershipOut */
    MembershipOut: {
      organization: components["schemas"]["OrganizationSummary"];
      /** Roles */
      roles: components["schemas"]["OrgRole"][];
    };
    /**
     * OrgRole
     * @enum {string}
     */
    OrgRole: "org_admin" | "instructor" | "lab_author" | "student";
    /** OrganizationSummary */
    OrganizationSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Is Content Publisher */
      is_content_publisher: boolean;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
    };
    /** ReadinessResponse */
    ReadinessResponse: {
      /** Checks */
      checks: {
        [key: string]: components["schemas"]["CheckResult"];
      };
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "unavailable";
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_me: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  health_live: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LivenessResponse"];
        };
      };
    };
  };
  health_ready: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessResponse"];
        };
      };
      /** @description A dependency is unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessResponse"];
        };
      };
    };
  };
}
