/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/audit-log": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Audit Log
     * @description Admin actions in the active organization, newest first (org admins; platform admins
     *     without an active organization see every organization).
     */
    get: operations["list_audit_log"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/batches": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Batches */
    get: operations["list_batches"];
    put?: never;
    /** Create Batch */
    post: operations["create_batch"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/batches/{batch_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Batch */
    get: operations["get_batch"];
    put?: never;
    post?: never;
    /**
     * Archive Batch
     * @description Archive (soft-delete): members and history are kept; no new members can be added.
     */
    delete: operations["archive_batch"];
    options?: never;
    head?: never;
    /** Update Batch */
    patch: operations["update_batch"];
    trace?: never;
  };
  "/api/v1/batches/{batch_id}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Batch Members */
    get: operations["list_batch_members"];
    put?: never;
    /** Add Batch Members */
    post: operations["add_batch_members"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/batches/{batch_id}/members/{user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove Batch Member */
    delete: operations["remove_batch_member"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/imports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Imports */
    get: operations["list_imports"];
    put?: never;
    /**
     * Create Import
     * @description Upload a CSV of students; processing continues in the background (poll GET /imports/{id}).
     */
    post: operations["create_import"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/imports/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Import */
    get: operations["get_import"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/imports/{job_id}/errors.csv": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Download Import Errors */
    get: operations["download_import_errors"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/invitations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Invitations */
    get: operations["list_invitations"];
    put?: never;
    /**
     * Create Invitation
     * @description Invite someone by email: grants the roles/batches now and emails a link to set a password
     *     (new accounts only).
     */
    post: operations["create_invitation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/invitations/{invitation_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke Invitation */
    delete: operations["revoke_invitation"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/invitations/{invitation_id}/resend": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Resend Invitation */
    post: operations["resend_invitation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Me
     * @description The signed-in user, their organizations and roles (for the org switcher), and the active
     *     organization's permissions.
     */
    get: operations["get_me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Members
     * @description Search members by name or email, filter by role or batch.
     */
    get: operations["list_members"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/members/{user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Member */
    get: operations["get_member"];
    put?: never;
    post?: never;
    /**
     * Remove Member
     * @description Remove from the organization (and all its batches).
     */
    delete: operations["remove_member"];
    options?: never;
    head?: never;
    /**
     * Update Member
     * @description Replace the member's roles in the active organization.
     */
    patch: operations["update_member"];
    trace?: never;
  };
  "/api/v1/organizations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Organizations */
    get: operations["list_organizations"];
    put?: never;
    /**
     * Create Organization
     * @description Create an organization (platform admins).
     */
    post: operations["create_organization"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/organizations/current": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Current Organization
     * @description The active organization (any member).
     */
    get: operations["get_current_organization"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/organizations/{organization_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Organization */
    get: operations["get_organization"];
    put?: never;
    post?: never;
    /**
     * Archive Organization
     * @description Archive (soft-delete): members lose access; data is kept.
     */
    delete: operations["archive_organization"];
    options?: never;
    head?: never;
    /** Update Organization */
    patch: operations["update_organization"];
    trace?: never;
  };
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Live */
    get: operations["health_live"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ready */
    get: operations["health_ready"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AuditEntryOut */
    AuditEntryOut: {
      /** Action */
      action: string;
      /** Actor Is Platform Admin */
      actor_is_platform_admin: boolean;
      /** Actor User Id */
      actor_user_id: string | null;
      /** After */
      after: unknown;
      /** Before */
      before: unknown;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Ip */
      ip: string | null;
      /** Organization Id */
      organization_id: string | null;
      /** Request Id */
      request_id: string | null;
      /** Target Id */
      target_id: string | null;
      /** Target Type */
      target_type: string;
    };
    /** BatchCreate */
    BatchCreate: {
      /**
       * Description
       * @default
       */
      description: string;
      /** Name */
      name: string;
    };
    /** BatchMembersAdd */
    BatchMembersAdd: {
      /** User Ids */
      user_ids: string[];
    };
    /** BatchMembersAddResult */
    BatchMembersAddResult: {
      /** Added */
      added: string[];
      /** Already Members */
      already_members: string[];
    };
    /** BatchOut */
    BatchOut: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Description */
      description: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Member Count */
      member_count: number;
      /** Name */
      name: string;
      /** Status */
      status: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** BatchUpdate */
    BatchUpdate: {
      /** Description */
      description?: string | null;
      /** Name */
      name?: string | null;
      /** Status */
      status?: ("active" | "archived") | null;
    };
    /** Body_create_import */
    Body_create_import: {
      /** Batch Id */
      batch_id?: string | null;
      /**
       * File
       * @description CSV with email and full_name columns
       */
      file: string;
    };
    /** CheckResult */
    CheckResult: {
      /** Error */
      error?: string | null;
      /** Latency Ms */
      latency_ms: number;
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "error";
    };
    /** CursorPage[AuditEntryOut] */
    CursorPage_AuditEntryOut_: {
      /** Items */
      items: components["schemas"]["AuditEntryOut"][];
      /**
       * Next Cursor
       * @description Opaque cursor for the next page; null when there are no more items.
       */
      next_cursor: string | null;
    };
    /** CursorPage[BatchOut] */
    CursorPage_BatchOut_: {
      /** Items */
      items: components["schemas"]["BatchOut"][];
      /**
       * Next Cursor
       * @description Opaque cursor for the next page; null when there are no more items.
       */
      next_cursor: string | null;
    };
    /** CursorPage[ImportJobOut] */
    CursorPage_ImportJobOut_: {
      /** Items */
      items: components["schemas"]["ImportJobOut"][];
      /**
       * Next Cursor
       * @description Opaque cursor for the next page; null when there are no more items.
       */
      next_cursor: string | null;
    };
    /** CursorPage[InvitationOut] */
    CursorPage_InvitationOut_: {
      /** Items */
      items: components["schemas"]["InvitationOut"][];
      /**
       * Next Cursor
       * @description Opaque cursor for the next page; null when there are no more items.
       */
      next_cursor: string | null;
    };
    /** CursorPage[MemberOut] */
    CursorPage_MemberOut_: {
      /** Items */
      items: components["schemas"]["MemberOut"][];
      /**
       * Next Cursor
       * @description Opaque cursor for the next page; null when there are no more items.
       */
      next_cursor: string | null;
    };
    /** CursorPage[OrganizationOut] */
    CursorPage_OrganizationOut_: {
      /** Items */
      items: components["schemas"]["OrganizationOut"][];
      /**
       * Next Cursor
       * @description Opaque cursor for the next page; null when there are no more items.
       */
      next_cursor: string | null;
    };
    /** ErrorBody */
    ErrorBody: {
      /** Code */
      code: string;
      /** Details */
      details?: unknown;
      /** Message */
      message: string;
    };
    /** ErrorResponse */
    ErrorResponse: {
      error: components["schemas"]["ErrorBody"];
    };
    /** ImportJobOut */
    ImportJobOut: {
      /** Batch Id */
      batch_id: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created Count */
      created_count: number;
      /** Error Count */
      error_count: number;
      /** Error Message */
      error_message: string | null;
      /** File Name */
      file_name: string;
      /** Finished At */
      finished_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Processed Rows */
      processed_rows: number;
      /** Skipped Count */
      skipped_count: number;
      /** Started At */
      started_at: string | null;
      /** Status */
      status: string;
      /** Total Rows */
      total_rows: number;
    };
    /** InvitationCreate */
    InvitationCreate: {
      /** Batch Ids */
      batch_ids?: string[];
      /**
       * Email
       * Format: email
       */
      email: string;
      /**
       * Full Name
       * @default
       */
      full_name: string;
      /** Roles */
      roles: components["schemas"]["OrgRole"][];
    };
    /** InvitationOut */
    InvitationOut: {
      /** Batch Ids */
      batch_ids: string[];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Email */
      email: string;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Invited By */
      invited_by: string | null;
      /** Roles */
      roles: components["schemas"]["OrgRole"][];
      /** Status */
      status: string;
      /** User Id */
      user_id: string | null;
    };
    /** LivenessResponse */
    LivenessResponse: {
      /**
       * Status
       * @constant
       */
      status: "ok";
    };
    /** MeResponse */
    MeResponse: {
      /** Active Organization Id */
      active_organization_id: string | null;
      /** Active Roles */
      active_roles: components["schemas"]["OrgRole"][];
      /** Is Platform Admin */
      is_platform_admin: boolean;
      /** Memberships */
      memberships: components["schemas"]["MembershipOut"][];
      /** Permissions */
      permissions: string[];
      user: components["schemas"]["MeUser"];
    };
    /** MeUser */
    MeUser: {
      /** Email */
      email: string;
      /** Full Name */
      full_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
    };
    /** MemberOut */
    MemberOut: {
      /** Batch Ids */
      batch_ids: string[];
      /** Roles */
      roles: components["schemas"]["OrgRole"][];
      user: components["schemas"]["UserOut"];
    };
    /** MemberUpdate */
    MemberUpdate: {
      /** Roles */
      roles: components["schemas"]["OrgRole"][];
    };
    /** MembershipOut */
    MembershipOut: {
      organization: components["schemas"]["OrganizationSummary"];
      /** Roles */
      roles: components["schemas"]["OrgRole"][];
    };
    /**
     * OrgRole
     * @enum {string}
     */
    OrgRole: "org_admin" | "instructor" | "lab_author" | "student";
    /** OrganizationCreate */
    OrganizationCreate: {
      /**
       * Is Content Publisher
       * @default false
       */
      is_content_publisher: boolean;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
    };
    /** OrganizationOut */
    OrganizationOut: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Is Content Publisher */
      is_content_publisher: boolean;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Status */
      status: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** OrganizationSummary */
    OrganizationSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Is Content Publisher */
      is_content_publisher: boolean;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
    };
    /** OrganizationUpdate */
    OrganizationUpdate: {
      /** Is Content Publisher */
      is_content_publisher?: boolean | null;
      /** Name */
      name?: string | null;
      /** Status */
      status?: ("active" | "archived") | null;
    };
    /** ReadinessResponse */
    ReadinessResponse: {
      /** Checks */
      checks: {
        [key: string]: components["schemas"]["CheckResult"];
      };
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "unavailable";
    };
    /** UserOut */
    UserOut: {
      /** Email */
      email: string;
      /** Full Name */
      full_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Status */
      status: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_audit_log: {
    parameters: {
      query?: {
        action?: string | null;
        actor_user_id?: string | null;
        target_type?: string | null;
        target_id?: string | null;
        limit?: number;
        cursor?: string | null;
      };
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CursorPage_AuditEntryOut_"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_batches: {
    parameters: {
      query?: {
        status?: ("active" | "archived") | null;
        limit?: number;
        cursor?: string | null;
      };
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CursorPage_BatchOut_"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_batch: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BatchCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BatchOut"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_batch: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path: {
        batch_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BatchOut"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  archive_batch: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path: {
        batch_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BatchOut"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_batch: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path: {
        batch_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BatchUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BatchOut"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_batch_members: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string | null;
      };
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path: {
        batch_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CursorPage_MemberOut_"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  add_batch_members: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path: {
        batch_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BatchMembersAdd"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BatchMembersAddResult"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  remove_batch_member: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path: {
        batch_id: string;
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_imports: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string | null;
      };
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CursorPage_ImportJobOut_"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_import: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_create_import"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportJobOut"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_import: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportJobOut"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  download_import_errors: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Per-row errors as CSV */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/csv": unknown;
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_invitations: {
    parameters: {
      query?: {
        status?: ("pending" | "accepted" | "revoked" | "expired") | null;
        limit?: number;
        cursor?: string | null;
      };
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CursorPage_InvitationOut_"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_invitation: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InvitationCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvitationOut"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  revoke_invitation: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path: {
        invitation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvitationOut"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  resend_invitation: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path: {
        invitation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvitationOut"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_me: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_members: {
    parameters: {
      query?: {
        q?: string | null;
        role?: components["schemas"]["OrgRole"] | null;
        batch_id?: string | null;
        limit?: number;
        cursor?: string | null;
      };
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CursorPage_MemberOut_"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_member: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberOut"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  remove_member: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_member: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MemberUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberOut"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_organizations: {
    parameters: {
      query?: {
        status?: ("active" | "archived") | null;
        limit?: number;
        cursor?: string | null;
      };
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CursorPage_OrganizationOut_"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_organization: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrganizationCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationOut"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_current_organization: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationOut"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_organization: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path: {
        organization_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationOut"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  archive_organization: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path: {
        organization_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationOut"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_organization: {
    parameters: {
      query?: never;
      header?: {
        /** @description Active organization for this request (from the org switcher). */
        "x-organization-id"?: string | null;
      };
      path: {
        organization_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrganizationUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationOut"];
        };
      };
      /** @description Client error */
      "4XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Server error */
      "5XX": {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  health_live: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LivenessResponse"];
        };
      };
    };
  };
  health_ready: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessResponse"];
        };
      };
      /** @description A dependency is unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessResponse"];
        };
      };
    };
  };
}
