"""Declarative base and shared column mixins.

Conventions (see CLAUDE.md):
- primary keys are UUIDv7, generated in the application
- timestamps are timestamptz, UTC
- tenant-owned tables use TenantMixin (indexed organization_id) and get an RLS policy in their
  migration
"""

from datetime import datetime
from uuid import UUID

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.ext.asyncio import AsyncAttrs
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from uuid_utils.compat import uuid7

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def new_id() -> UUID:
    """Time-ordered UUIDv7: index-friendly and usable as a keyset pagination key."""
    return uuid7()


def uuid7_floor(at: datetime) -> UUID:
    """The smallest UUIDv7 for the millisecond `at` (an aware datetime). Every id generated at or
    after `at` compares >= it, so a time range becomes an id range on the primary key (ids are
    generated by the app when the row is written; `created_at` may differ by milliseconds)."""
    ms = int(at.timestamp() * 1000)
    # 48-bit timestamp | version 7 | zero rand_a | RFC 4122 variant (0b10) | zero rand_b
    return UUID(int=(ms << 80) | (0x7 << 76) | (0b10 << 62))


class Base(AsyncAttrs, DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
    type_annotation_map = {datetime: DateTime(timezone=True)}  # noqa: RUF012


class UUIDPrimaryKeyMixin:
    id: Mapped[UUID] = mapped_column(primary_key=True, default=new_id)


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(server_default=func.now(), onupdate=func.now())


class TenantMixin:
    organization_id: Mapped[UUID] = mapped_column(index=True)
