"""Write the stylesheet for highlighted code in notes (Pygments' class-based token styles).

python -m app.cli.export_notes_css <output.css>

The API renders code blocks to `<pre class="highlight"><code><span class="k">...` at publish time;
the web app ships this CSS next to that HTML (apps/web/src/styles/notes-code.css, via
`make gen-api`). tests/test_notes_css.py fails when the committed copy is stale.
"""

import sys
from pathlib import Path

from app.modules.courses.notes import stylesheet

HEADER = "/* Generated by `make gen-api` (python -m app.cli.export_notes_css). Do not edit. */\n"


def css() -> str:
    return HEADER + stylesheet() + "\n"


def main() -> None:
    if len(sys.argv) != 2:  # noqa: PLR2004
        sys.exit("usage: python -m app.cli.export_notes_css <output.css>")
    Path(sys.argv[1]).write_text(css(), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
