"""Assessment foundation and sensitive learning-event outbox isolation.

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-04 13:08:49.647712+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.db.rls import APP_ROLE, IN_CURRENT_ORG, PLATFORM_ADMIN, enable_rls, policy

revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_banks",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("revision", sa.Integer(), server_default="1", nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_question_banks_revision")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_question_banks_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_banks")),
        sa.UniqueConstraint(
            "id", "organization_id", name=op.f("uq_question_banks_id_organization_id")
        ),
    )
    op.create_index(
        "ix_question_banks_org_archived_id",
        "question_banks",
        ["organization_id", "archived_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_banks_organization_id"),
        "question_banks",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "questions",
        sa.Column("bank_id", sa.Uuid(), nullable=False),
        sa.Column("question_type", sa.String(length=20), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column(
            "options", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("revision", sa.Integer(), server_default="1", nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "question_type IN ('mcq_single', 'mcq_multi', 'fill_blank')",
            name=op.f("ck_questions_type"),
        ),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_questions_revision")),
        sa.ForeignKeyConstraint(
            ["bank_id", "organization_id"],
            ["question_banks.id", "question_banks.organization_id"],
            name=op.f("fk_questions_bank_id_question_banks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_questions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
        sa.UniqueConstraint("id", "organization_id", name=op.f("uq_questions_id_organization_id")),
    )
    op.create_index(
        "ix_questions_bank_org", "questions", ["bank_id", "organization_id"], unique=False
    )
    op.create_index(
        "ix_questions_bank_type_id", "questions", ["bank_id", "question_type", "id"], unique=False
    )
    op.create_index(
        op.f("ix_questions_organization_id"), "questions", ["organization_id"], unique=False
    )
    op.create_table(
        "question_keys",
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("answer_key", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("explanation", sa.Text(), server_default="", nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_question_keys_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id", "organization_id"],
            ["questions.id", "questions.organization_id"],
            name=op.f("fk_question_keys_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("question_id", name=op.f("pk_question_keys")),
    )
    op.create_index(
        op.f("ix_question_keys_organization_id"), "question_keys", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_question_keys_question_org",
        "question_keys",
        ["question_id", "organization_id"],
        unique=False,
    )
    op.create_table(
        "question_skills",
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_question_skills_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id", "organization_id"],
            ["questions.id", "questions.organization_id"],
            name=op.f("fk_question_skills_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_question_skills_skill_id_skills"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("question_id", "skill_id", name=op.f("pk_question_skills")),
    )
    op.create_index(
        op.f("ix_question_skills_organization_id"),
        "question_skills",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_question_skills_question_org",
        "question_skills",
        ["question_id", "organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_skills_skill_id"), "question_skills", ["skill_id"], unique=False
    )
    op.create_table(
        "quiz_versions",
        sa.Column("quiz_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("course_version_id", sa.Uuid(), nullable=False),
        sa.Column("lesson_id", sa.Uuid(), nullable=False),
        sa.Column("major_version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("selection_mode", sa.String(length=10), nullable=False),
        sa.Column("selection", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("max_marks", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("pass_marks", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("time_limit_seconds", sa.Integer(), nullable=False),
        sa.Column("attempts_allowed", sa.Integer(), nullable=False),
        sa.Column("randomize_order", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("reveal_mode", sa.String(length=20), server_default="score_only", nullable=False),
        sa.Column(
            "reveal_timing", sa.String(length=30), server_default="immediately", nullable=False
        ),
        sa.CheckConstraint(
            "reveal_mode IN ('score_only', 'correct_answers', 'explanations')",
            name=op.f("ck_quiz_versions_reveal_mode"),
        ),
        sa.CheckConstraint(
            "reveal_timing IN ('immediately', 'after_attempts_exhausted')",
            name=op.f("ck_quiz_versions_reveal_timing"),
        ),
        sa.CheckConstraint(
            "selection_mode IN ('manual', 'bank')", name=op.f("ck_quiz_versions_selection_mode")
        ),
        sa.CheckConstraint(
            "attempts_allowed BETWEEN 1 AND 100", name=op.f("ck_quiz_versions_attempts_allowed")
        ),
        sa.CheckConstraint("major_version >= 1", name=op.f("ck_quiz_versions_major_version")),
        sa.CheckConstraint(
            "max_marks > 0 AND pass_marks > 0 AND pass_marks <= max_marks",
            name=op.f("ck_quiz_versions_marks"),
        ),
        sa.CheckConstraint(
            "time_limit_seconds BETWEEN 1 AND 86400", name=op.f("ck_quiz_versions_time_limit")
        ),
        sa.ForeignKeyConstraint(
            ["course_id", "organization_id"],
            ["courses.id", "courses.organization_id"],
            name=op.f("fk_quiz_versions_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["course_version_id"],
            ["course_versions.id"],
            name=op.f("fk_quiz_versions_course_version_id_course_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_quiz_versions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_versions")),
        sa.UniqueConstraint(
            "course_version_id",
            "lesson_id",
            name=op.f("uq_quiz_versions_course_version_id_lesson_id"),
        ),
        sa.UniqueConstraint(
            "id", "organization_id", name=op.f("uq_quiz_versions_id_organization_id")
        ),
    )
    op.create_index(
        "ix_quiz_versions_course_org",
        "quiz_versions",
        ["course_id", "organization_id"],
        unique=False,
    )
    op.create_index("ix_quiz_versions_lesson_id", "quiz_versions", ["lesson_id"], unique=False)
    op.create_index(
        op.f("ix_quiz_versions_organization_id"), "quiz_versions", ["organization_id"], unique=False
    )
    op.create_index("ix_quiz_versions_quiz_id", "quiz_versions", ["quiz_id"], unique=False)
    op.create_table(
        "quiz_attempts",
        sa.Column("enrollment_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("lesson_id", sa.Uuid(), nullable=False),
        sa.Column("quiz_version_id", sa.Uuid(), nullable=False),
        sa.Column("major_version", sa.Integer(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("question_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("state", sa.String(length=20), server_default="in_progress", nullable=False),
        sa.Column("revision", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("max_marks", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(state = 'submitted' AND submitted_at IS NOT NULL AND score IS NOT NULL "
            "AND passed IS NOT NULL AND score BETWEEN 0 AND max_marks) OR "
            "(state IN ('in_progress', 'abandoned') AND score IS NULL "
            "AND passed IS NULL AND submitted_at IS NULL)",
            name=op.f("ck_quiz_attempts_result_state"),
        ),
        sa.CheckConstraint(
            "state IN ('in_progress', 'submitted', 'abandoned')",
            name=op.f("ck_quiz_attempts_state"),
        ),
        sa.CheckConstraint(
            "cardinality(question_ids) >= 1", name=op.f("ck_quiz_attempts_questions")
        ),
        sa.CheckConstraint(
            "expires_at > started_at AND max_marks > 0", name=op.f("ck_quiz_attempts_limits")
        ),
        sa.CheckConstraint(
            "revision >= 1 AND attempt_number >= 1 AND major_version >= 1",
            name=op.f("ck_quiz_attempts_numbers"),
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_quiz_attempts_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["enrollment_id"],
            ["enrollments.id"],
            name=op.f("fk_quiz_attempts_enrollment_id_enrollments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_quiz_attempts_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["quiz_version_id"],
            ["quiz_versions.id"],
            name=op.f("fk_quiz_attempts_quiz_version_id_quiz_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_quiz_attempts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_attempts")),
        sa.UniqueConstraint(
            "enrollment_id",
            "lesson_id",
            "major_version",
            "attempt_number",
            name=op.f("uq_quiz_attempts_enrollment_id_lesson_id_major_version_attempt_number"),
        ),
        sa.UniqueConstraint(
            "id", "organization_id", name=op.f("uq_quiz_attempts_id_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_quiz_attempts_course_id"), "quiz_attempts", ["course_id"], unique=False
    )
    op.create_index(
        op.f("ix_quiz_attempts_enrollment_id"), "quiz_attempts", ["enrollment_id"], unique=False
    )
    op.create_index(
        "ix_quiz_attempts_expiry",
        "quiz_attempts",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("state = 'in_progress'"),
    )
    op.create_index(
        "ix_quiz_attempts_org_user_id",
        "quiz_attempts",
        ["organization_id", "user_id", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quiz_attempts_organization_id"), "quiz_attempts", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_quiz_attempts_quiz_version_id"), "quiz_attempts", ["quiz_version_id"], unique=False
    )
    op.create_index(op.f("ix_quiz_attempts_user_id"), "quiz_attempts", ["user_id"], unique=False)
    op.create_index(
        "uq_quiz_attempts_active",
        "quiz_attempts",
        ["enrollment_id", "lesson_id", "major_version"],
        unique=True,
        postgresql_where=sa.text("state = 'in_progress'"),
    )
    op.create_table(
        "quiz_version_questions",
        sa.Column("quiz_version_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("question_type", sa.String(length=20), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("skill_ids", postgresql.ARRAY(sa.Uuid()), server_default="{}", nullable=False),
        sa.Column("marks", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "question_type IN ('mcq_single', 'mcq_multi', 'fill_blank')",
            name=op.f("ck_quiz_version_questions_type"),
        ),
        sa.CheckConstraint("marks > 0", name=op.f("ck_quiz_version_questions_marks")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_quiz_version_questions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["quiz_version_id", "organization_id"],
            ["quiz_versions.id", "quiz_versions.organization_id"],
            name=op.f("fk_quiz_version_questions_quiz_version_id_quiz_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_version_questions")),
        sa.UniqueConstraint(
            "id", "organization_id", name=op.f("uq_quiz_version_questions_id_organization_id")
        ),
        sa.UniqueConstraint(
            "quiz_version_id",
            "question_id",
            name=op.f("uq_quiz_version_questions_quiz_version_id_question_id"),
        ),
    )
    op.create_index(
        op.f("ix_quiz_version_questions_organization_id"),
        "quiz_version_questions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_quiz_version_questions_version_org",
        "quiz_version_questions",
        ["quiz_version_id", "organization_id"],
        unique=False,
    )
    op.create_table(
        "quizzes",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("lesson_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("selection_mode", sa.String(length=10), nullable=False),
        sa.Column("selection", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("max_marks", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("pass_marks", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("time_limit_seconds", sa.Integer(), nullable=False),
        sa.Column("attempts_allowed", sa.Integer(), nullable=False),
        sa.Column("randomize_order", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("reveal_mode", sa.String(length=20), server_default="score_only", nullable=False),
        sa.Column(
            "reveal_timing", sa.String(length=30), server_default="immediately", nullable=False
        ),
        sa.CheckConstraint(
            "reveal_mode IN ('score_only', 'correct_answers', 'explanations')",
            name=op.f("ck_quizzes_reveal_mode"),
        ),
        sa.CheckConstraint(
            "reveal_timing IN ('immediately', 'after_attempts_exhausted')",
            name=op.f("ck_quizzes_reveal_timing"),
        ),
        sa.CheckConstraint(
            "selection_mode IN ('manual', 'bank')", name=op.f("ck_quizzes_selection_mode")
        ),
        sa.CheckConstraint(
            "attempts_allowed BETWEEN 1 AND 100", name=op.f("ck_quizzes_attempts_allowed")
        ),
        sa.CheckConstraint(
            "max_marks > 0 AND pass_marks > 0 AND pass_marks <= max_marks",
            name=op.f("ck_quizzes_marks"),
        ),
        sa.CheckConstraint(
            "time_limit_seconds BETWEEN 1 AND 86400", name=op.f("ck_quizzes_time_limit")
        ),
        sa.ForeignKeyConstraint(
            ["course_id", "organization_id"],
            ["courses.id", "courses.organization_id"],
            name=op.f("fk_quizzes_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
            name=op.f("fk_quizzes_lesson_id_lessons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_quizzes_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quizzes")),
        sa.UniqueConstraint("lesson_id", name=op.f("uq_quizzes_lesson_id")),
    )
    op.create_index(
        "ix_quizzes_course_org", "quizzes", ["course_id", "organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_quizzes_organization_id"), "quizzes", ["organization_id"], unique=False
    )
    op.create_table(
        "quiz_answers",
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("answer", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("revision", sa.Integer(), server_default="1", nullable=False),
        sa.Column("awarded_marks", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "awarded_marks IS NULL OR awarded_marks >= 0", name=op.f("ck_quiz_answers_marks")
        ),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_quiz_answers_revision")),
        sa.ForeignKeyConstraint(
            ["attempt_id", "organization_id"],
            ["quiz_attempts.id", "quiz_attempts.organization_id"],
            name=op.f("fk_quiz_answers_attempt_id_quiz_attempts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_quiz_answers_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["quiz_version_questions.id"],
            name=op.f("fk_quiz_answers_question_id_quiz_version_questions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_answers")),
        sa.UniqueConstraint(
            "attempt_id", "question_id", name=op.f("uq_quiz_answers_attempt_id_question_id")
        ),
    )
    op.create_index(
        "ix_quiz_answers_attempt_org",
        "quiz_answers",
        ["attempt_id", "organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quiz_answers_organization_id"), "quiz_answers", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_quiz_answers_question_id"), "quiz_answers", ["question_id"], unique=False
    )
    op.create_table(
        "quiz_version_keys",
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("answer_key", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("explanation", sa.Text(), server_default="", nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_quiz_version_keys_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id", "organization_id"],
            ["quiz_version_questions.id", "quiz_version_questions.organization_id"],
            name=op.f("fk_quiz_version_keys_question_id_quiz_version_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("question_id", name=op.f("pk_quiz_version_keys")),
    )
    op.create_index(
        op.f("ix_quiz_version_keys_organization_id"),
        "quiz_version_keys",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_quiz_version_keys_question_org",
        "quiz_version_keys",
        ["question_id", "organization_id"],
        unique=False,
    )
    _security()


def downgrade() -> None:
    _drop_security()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_quiz_version_keys_question_org", table_name="quiz_version_keys")
    op.drop_index(op.f("ix_quiz_version_keys_organization_id"), table_name="quiz_version_keys")
    op.drop_table("quiz_version_keys")
    op.drop_index(op.f("ix_quiz_answers_question_id"), table_name="quiz_answers")
    op.drop_index(op.f("ix_quiz_answers_organization_id"), table_name="quiz_answers")
    op.drop_index("ix_quiz_answers_attempt_org", table_name="quiz_answers")
    op.drop_table("quiz_answers")
    op.drop_index(op.f("ix_quizzes_organization_id"), table_name="quizzes")
    op.drop_index("ix_quizzes_course_org", table_name="quizzes")
    op.drop_table("quizzes")
    op.drop_index("ix_quiz_version_questions_version_org", table_name="quiz_version_questions")
    op.drop_index(
        op.f("ix_quiz_version_questions_organization_id"), table_name="quiz_version_questions"
    )
    op.drop_table("quiz_version_questions")
    op.drop_index(
        "uq_quiz_attempts_active",
        table_name="quiz_attempts",
        postgresql_where=sa.text("state = 'in_progress'"),
    )
    op.drop_index(op.f("ix_quiz_attempts_user_id"), table_name="quiz_attempts")
    op.drop_index(op.f("ix_quiz_attempts_quiz_version_id"), table_name="quiz_attempts")
    op.drop_index(op.f("ix_quiz_attempts_organization_id"), table_name="quiz_attempts")
    op.drop_index("ix_quiz_attempts_org_user_id", table_name="quiz_attempts")
    op.drop_index(
        "ix_quiz_attempts_expiry",
        table_name="quiz_attempts",
        postgresql_where=sa.text("state = 'in_progress'"),
    )
    op.drop_index(op.f("ix_quiz_attempts_enrollment_id"), table_name="quiz_attempts")
    op.drop_index(op.f("ix_quiz_attempts_course_id"), table_name="quiz_attempts")
    op.drop_table("quiz_attempts")
    op.drop_index("ix_quiz_versions_quiz_id", table_name="quiz_versions")
    op.drop_index(op.f("ix_quiz_versions_organization_id"), table_name="quiz_versions")
    op.drop_index("ix_quiz_versions_lesson_id", table_name="quiz_versions")
    op.drop_index("ix_quiz_versions_course_org", table_name="quiz_versions")
    op.drop_table("quiz_versions")
    op.drop_index(op.f("ix_question_skills_skill_id"), table_name="question_skills")
    op.drop_index("ix_question_skills_question_org", table_name="question_skills")
    op.drop_index(op.f("ix_question_skills_organization_id"), table_name="question_skills")
    op.drop_table("question_skills")
    op.drop_index("ix_question_keys_question_org", table_name="question_keys")
    op.drop_index(op.f("ix_question_keys_organization_id"), table_name="question_keys")
    op.drop_table("question_keys")
    op.drop_index(op.f("ix_questions_organization_id"), table_name="questions")
    op.drop_index("ix_questions_bank_type_id", table_name="questions")
    op.drop_index("ix_questions_bank_org", table_name="questions")
    op.drop_table("questions")
    op.drop_index(op.f("ix_question_banks_organization_id"), table_name="question_banks")
    op.drop_index("ix_question_banks_org_archived_id", table_name="question_banks")
    op.drop_table("question_banks")
    # ### end Alembic commands ###


EDITOR = (
    f"({PLATFORM_ADMIN} OR ({IN_CURRENT_ORG} AND "
    "app.current_user_has_role(app.current_org_id(), '{instructor,org_admin}'::text[])))"
)
DEFINER = "LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public"
HELPERS = (
    "app.learning_event_owned(uuid,uuid)",
    "app.quiz_version_readable(uuid)",
    "app.quiz_attempt_readable(uuid)",
    "app.quiz_question_readable(uuid)",
    "app.quiz_reveal_allowed(uuid)",
    "app.quiz_attempt_solutions(uuid)",
)


def _security() -> None:
    # Enrollment-owned SQL interface: historical events use ownership, not the payload's
    # untrusted user_id. Current quiz access additionally requires active/batch authorization.
    op.execute(f"""
        CREATE FUNCTION app.learning_event_owned(enrollment uuid, org uuid) RETURNS boolean
        {DEFINER} AS $$
          SELECT org = app.current_org_id() AND app.current_user_is_member(org) AND EXISTS (
            SELECT 1 FROM public.enrollments e WHERE e.id = enrollment
              AND e.organization_id = org AND e.user_id = app.current_user_id()
          )
        $$
    """)
    op.execute(f"""
        CREATE FUNCTION app.quiz_version_readable(version uuid) RETURNS boolean
        {DEFINER} AS $$
          SELECT EXISTS (
            SELECT 1 FROM public.quiz_versions q
            JOIN public.course_versions cv ON cv.id = q.course_version_id
              AND cv.course_id = q.course_id AND cv.organization_id = q.organization_id
              AND cv.major = q.major_version
            JOIN public.course_version_lessons vl ON vl.version_id = cv.id
              AND vl.lesson_id = q.lesson_id AND vl.lesson_type = 'quiz'
            WHERE q.id = version AND (
              app.current_user_is_platform_admin() OR
              (app.current_user_has_role(q.organization_id, '{{instructor,org_admin}}'::text[])
                AND q.organization_id = app.current_org_id()) OR
              (app.course_readable(q.course_id) AND
                app.current_user_has_role(app.current_org_id(), '{{instructor,org_admin}}'::text[]))
              OR EXISTS (
                SELECT 1 FROM public.enrollments e WHERE e.course_id = q.course_id
                  AND e.organization_id = app.current_org_id()
                  AND e.user_id = app.current_user_id() AND e.status = 'active'
                  AND e.major_version = q.major_version
                  AND app.current_user_has_role(e.organization_id, '{{student}}'::text[])
                  AND app.course_readable(e.course_id)
              )
            )
          )
        $$
    """)
    op.execute(f"""
        CREATE FUNCTION app.quiz_attempt_readable(attempt uuid) RETURNS boolean
        {DEFINER} AS $$
          SELECT EXISTS (
            SELECT 1 FROM public.quiz_attempts a
            JOIN public.enrollments e ON e.id = a.enrollment_id
              AND e.organization_id = a.organization_id AND e.user_id = a.user_id
              AND e.course_id = a.course_id
            JOIN public.quiz_versions q ON q.id = a.quiz_version_id
              AND q.course_id = a.course_id AND q.lesson_id = a.lesson_id
              AND q.major_version = a.major_version
            WHERE a.id = attempt AND (
              app.current_user_is_platform_admin() OR
              (a.organization_id = app.current_org_id() AND
                app.current_user_has_role(a.organization_id, '{{instructor,org_admin}}'::text[]))
              OR (a.organization_id = app.current_org_id() AND a.user_id = app.current_user_id()
                AND e.status = 'active' AND e.major_version = a.major_version
                AND app.current_user_has_role(a.organization_id, '{{student}}'::text[])
                AND app.course_readable(e.course_id))
            )
          )
        $$
    """)
    op.execute(f"""
        CREATE FUNCTION app.quiz_question_readable(question uuid) RETURNS boolean
        {DEFINER} AS $$
          SELECT EXISTS (
            SELECT 1 FROM public.quiz_version_questions p
            JOIN public.quiz_versions q ON q.id = p.quiz_version_id
            WHERE p.id = question AND (
              app.current_user_is_platform_admin() OR
              (app.quiz_version_readable(q.id) AND
                app.current_user_has_role(app.current_org_id(), '{{instructor,org_admin}}'::text[]))
              OR EXISTS (
                SELECT 1 FROM public.quiz_attempts a WHERE a.quiz_version_id = q.id
                  AND p.id = ANY(a.question_ids) AND app.quiz_attempt_readable(a.id)
              )
            )
          )
        $$
    """)
    op.execute(f"""
        CREATE FUNCTION app.quiz_reveal_allowed(attempt uuid) RETURNS boolean
        {DEFINER} AS $$
          SELECT EXISTS (
            SELECT 1 FROM public.quiz_attempts a
            JOIN public.quiz_versions q ON q.id = a.quiz_version_id
            WHERE a.id = attempt AND a.organization_id = app.current_org_id()
              AND a.user_id = app.current_user_id() AND app.quiz_attempt_readable(a.id)
              AND a.state = 'submitted' AND q.reveal_mode <> 'score_only'
              AND (q.reveal_timing = 'immediately' OR (
                (SELECT count(*) FROM public.quiz_attempts used
                  WHERE used.enrollment_id = a.enrollment_id AND used.lesson_id = a.lesson_id
                    AND used.major_version = a.major_version) >= q.attempts_allowed
                AND NOT EXISTS (SELECT 1 FROM public.quiz_attempts active
                  WHERE active.enrollment_id = a.enrollment_id AND active.lesson_id = a.lesson_id
                    AND active.major_version = a.major_version AND active.state = 'in_progress')
              ))
          )
        $$
    """)
    op.execute(f"""
        CREATE FUNCTION app.quiz_attempt_solutions(attempt uuid)
        RETURNS TABLE(question_id uuid, answer_key jsonb, explanation text)
        {DEFINER} AS $$
          SELECT p.id, k.answer_key,
            CASE WHEN q.reveal_mode = 'explanations' THEN k.explanation ELSE NULL END
          FROM public.quiz_attempts a
          JOIN public.quiz_versions q ON q.id = a.quiz_version_id
          JOIN public.quiz_version_questions p ON p.quiz_version_id = q.id
            AND p.id = ANY(a.question_ids)
          JOIN public.quiz_version_keys k ON k.question_id = p.id
          WHERE a.id = attempt AND app.quiz_reveal_allowed(a.id)
          ORDER BY array_position(a.question_ids, p.id)
        $$
    """)
    for signature in HELPERS:
        op.execute(f"REVOKE ALL ON FUNCTION {signature} FROM PUBLIC")
        op.execute(f"GRANT EXECUTE ON FUNCTION {signature} TO {APP_ROLE}")

    for table in ("question_banks", "questions", "question_keys", "quizzes", "question_skills"):
        enable_rls(table)
        policy(table, "select", using=EDITOR, to=APP_ROLE)
        policy(table, "insert", check=EDITOR, to=APP_ROLE)
        if table != "question_skills":
            policy(table, "update", using=EDITOR, check=EDITOR, to=APP_ROLE)
        policy(table, "delete", using=EDITOR, to=APP_ROLE)
    op.execute(f"REVOKE UPDATE ON question_skills FROM {APP_ROLE}")
    for table, readable in (
        ("quiz_versions", "app.quiz_version_readable(id)"),
        ("quiz_version_questions", "app.quiz_question_readable(id)"),
        ("quiz_version_keys", EDITOR),
    ):
        enable_rls(table)
        policy(table, "select", using=readable, to=APP_ROLE)
        policy(table, "insert", check=EDITOR, to=APP_ROLE)
        op.execute(f"REVOKE UPDATE, DELETE ON {table} FROM {APP_ROLE}")
    for table, readable in (
        ("quiz_attempts", "app.quiz_attempt_readable(id)"),
        ("quiz_answers", "app.quiz_attempt_readable(attempt_id)"),
    ):
        enable_rls(table)
        policy(table, "select", using=readable, to=APP_ROLE)
        # Step 3 adds validated SECURITY DEFINER mutation functions, never broad grants.
        op.execute(f"REVOKE INSERT, UPDATE, DELETE ON {table} FROM {APP_ROLE}")

    _outbox_select(repaired=True)


def _outbox_select(*, repaired: bool) -> None:
    scope = f"({IN_CURRENT_ORG} OR (organization_id IS NULL AND {PLATFORM_ADMIN}))"
    if repaired:
        scope += f""" AND (
            (aggregate_type NOT IN ('enrollment', 'video_progress') AND
              event_type NOT IN ('assignment_graded', 'assignment_submitted',
                'quiz_attempt_submitted', 'lesson_completed', 'video_progress',
                'enrollment_created', 'enrollment_version_changed'))
            OR {PLATFORM_ADMIN}
            OR (organization_id = app.current_org_id() AND
              app.current_user_has_role(organization_id, '{{instructor,org_admin}}'::text[]))
            OR app.learning_event_owned(aggregate_id, organization_id)
        )"""
    op.execute("DROP POLICY outbox_events_select ON outbox_events")
    policy("outbox_events", "select", using=scope, to=APP_ROLE)


def _drop_security() -> None:
    _outbox_select(repaired=False)
    # Tables are dropped next; remove policies before the helper functions they reference.
    for table in ("quiz_answers", "quiz_attempts", "quiz_versions", "quiz_version_questions"):
        op.execute(f"DROP POLICY {table}_select ON {table}")
    for signature in reversed(HELPERS):
        op.execute(f"DROP FUNCTION {signature}")
